### ISSUE TITLE
How does mob-recon handle integrated plasmids?

### ISSUE THREAD

**Issue by nickp60** [phac-nml/mob-suite#12]
Hi, I am trying to detect integrated plasmids in a single sequence (working with a test genome).  I get a single hit in the `contigs_report.txt` file, but the fields for "contig_match_start" and "contig_match_end" are empty. Is there a way to get the start/end coords from mob-suite?  The actual assemblies I will be working with will be more fragmented, but it would still be nice to have the coords...

Thanks in advance!

**Comment by jrober84** [comment]
Hi,

MOB-recon treats integrated plasmids and free-living plasmids the same and is not explicitly determining the boundaries of the elements in the sequence.  In terms of providing MOB-suite a complete and closed chromosome with an integrated plasmid, it would just report the whole thing as a plasmid.  Since this is a very unlikely scenario with draft assemblies using illumina, the component contigs of the plasmid would be unlikely to resolve in a large contig with the chromosome. The contig_match_start and contig_match_end are only for the identification of repetitive sequences such as IS elements. If they are blank then that means that none were found. I will update the documentation to make this more clear.

Identifying the boundaries of a plasmid integrated into the chromosome is much trickier.  The contig report file does not report the best blast hits for a contig to a reference plasmid since this report would contain many which have no hit to the references because they are chromosome in origin.  

What are you planning on doing with the integrated plasmid information? Are you just trying to identify its presence or are you delineate its boundaries more?  If you are just interested in the blast results you could use the --keep_tmp flag and then take the contig_blast_results.txt file and that will give you the unfiltered blast hits to the reference.

**Comment by nickp60** [comment]
Hi @jrober84 , thanks for the info, that does clarify things.  Ideally, I would like to use the tool to extract integrated phage sequences from both draft and "complete" assemblies.  What are the column headers for the `contig_blast_results.txt` file? I'm not familiar with the legacy blast output, it looks different from the current blast -6 output format...

**Comment by jrober84** [comment]
The fields for the output are: qseqid,sseqid,qlen,slen,qstart,qend,sstart,send,length,mismatch,pident,qcovhsp,qcovs,sstrand,evalue,bitscore.  Thanks for the feedback on that, I will work on updating the documentation for this. Do you have some accessions for plasmids inserted into the chromosome that you are interested in?

**Comment by nickp60** [comment]
Thanks! The one I have been playing with is the chromosome for [this E. coli](https://www.ncbi.nlm.nih.gov/nuccore/CP003289.1) -- the chromosome gets called as a plasmid, and I want to see which regions are being identified.

**Comment by jrober84** [comment]
I have updated the documentation with the header information but integrated plasmid identification is a different problem which would need to be investigated separately for an implementation
