### ISSUE TITLE
[Question] Could MOB-suite be used in metagenomics data

### ISSUE THREAD

**Issue by llk578496** [phac-nml/mob-suite#144]
Hello! We have some Nanopore sequencing data for investigating urban metagenomics. We would like to find out the associations between mobile genetics elements and AMR genes. May we ask if `MOB-suite` could be used in this case?

Thanks a lot!

Eddie

**Comment by jrober84** [comment]
It is not recommended to use MOB-recon on metagenomics since a key assumption it makes is that there is only one version of a mob-cluster present. This would likely cause plasmids which have multiple versions assembling of the MOB-cluster failing to get classified or a jumbled mess of contigs. You can definitely use MOB-typer on the reconstructed contigs you get from another software.   We are contemplating extending functionality for plasmids in metagenomes but that is not something we have the resources to work on at present.

**Comment by fconstancias** [comment]
I am curious if there is any update on this?
