### ISSUE TITLE
Pandas version issue when installing using conda/mamba

### ISSUE THREAD

**Issue by tianrenmaogithub** [phac-nml/mob-suite#154]
I used mamba to install it with python version 3.9, but it installed pandas 2.1.3 and returned an error.
You required pandas >= 0.22.0,<=1.05 but it was not effective in conda. 
I solved it by manually installing pandas 1.0.5 in python 3.8.

**Comment by kbessonov1984** [comment]
We restricted pandas version due to `EmptyDataError` we had before. Since then we updated code to make it compatible with newer pandas versions but did not extensively tested it. Please install `mob_suite` in a separate environment to avoid pandas versions conflicting requirements.

**Comment by kbessonov1984** [comment]
Relaxed pandas to 1.5.3 or lower version in mob_suite v3.1.8 build 1  conda recipe (https://github.com/bioconda/bioconda-recipes/pull/44947) to make it more install flexible (https://anaconda.org/bioconda/mob_suite/files). pandas >=1.5.3 is not supported yet in the mob_suite code and would cause issues due to deprecation of some parameters in some key functions.
