### ISSUE TITLE
I cannot install MOBsuite to my environment

### ISSUE THREAD

**Issue by zeineppu97** [phac-nml/mob-suite#169]
Hello,
I'm a newbie in programming and need help installing MOBsuite in my conda environment. I've opened a new environment to install the specific requirements. Here is what I installed before installing MOBsuite:
python=3.8
pandas=1.0.5
numpy=1.19.0

I also have the necessary channels. However, it gets stuck in the solving environment stage when I run `conda install -c bioconda mob_suite -y` (I've tried without -y too). It stuck for two days in this state, but I've never had any response. I am trying to figure out what is wrong. I have to solve it soon because I have to finish my thesis in a week and classify my plasmids for my result section. Can you help me?

**Comment by danielesmedile** [comment]
Same problem here, installation via bioconda keeps getting stuck after launching
```
conda install -c bioconda mob_suite
``` 
(Executing transaction is endlessly loading). 
Has anyone figured this out yet?

**Comment by e-jkl** [comment]
I can confirm there is a problem in solving the environment as well.

**Comment by zeineppu97** [comment]
I successfully installed MOBsuite via pip :) There is a problem with the conda installation.

**Comment by e-jkl** [comment]
LibMambaUnsatisfiableError: Encountered problems while solving:
  - package pycurl-7.43.0.5-py36h5be270d_3 requires libcurl >=7.71.1,<9.0a0, but none of the providers can be installed

**Comment by zeineppu97** [comment]
I'm pretty new to coding, so I'm not sure how to solve this specific error :') The thing that I did was create a new environment in conda with python=3.8 and open it. Then, I installed pandas=1.0.5 (the version was written wrong in the requirements section of MOBsuite) and numpy=1.19.0 (suggested by a developer in one of the issues here). Then, I installed MOBsuite via pip, and it worked. You could ask it to ChatGPT, too, if no one answers here.

**Comment by e-jkl** [comment]
@zeineppu97 This is great - it worked. Thank you so much!

**Comment by zeineppu97** [comment]
I'm glad it did work ^^ Good luck with your analysis!

**Comment by NerisGarcia** [comment]
Hi,

I ran into the same issue, and it seems the conflict is mainly due to the version of pandas. By default, Conda installs a higher version than what MOBsuite requires. To resolve this, I created a new environment and first installed all the dependencies with their default versions, except for pandas, which I set to version 1.0.0. and python which I installed version 3.8. After that, running `conda install -c bioconda mob_suite` worked smoothly, and it automatically adjusted numpy to the required version.

Hope this helps!

**Comment by e-jkl** [comment]
@NerisGarcia Good to hear - will note that in my next installation attempt!

**Comment by pdy1084** [comment]
I run into a similar issue and also worked for me installing pandas 1.0.0 and biopython 1.84 from conda-forge (as the latest version from bioconda is  biopython 1.70).  So in a single command would be:
`
conda create -n mob_suite mob_suite pandas==1.0.0 conda-forge::biopython`

**Comment by kbessonov1984** [comment]
Thank you for looking into this. The new version 3.1.9 relaxed pandas requirement to 1.5.3 and should work without any extra hoops to jump. You can always check what are the minimum requirements at conda recipe 
 repo https://github.com/bioconda/bioconda-recipes/blob/master/recipes/mob_suite/meta.yaml and setup file https://github.com/phac-nml/mob-suite/blob/master/setup.py. I also recommend using a new environment solver `mamba` instead of `conda` as it is faster. We will be looking into migration to `pandas 2.0` in the future to avoid any issues. Also will need to bump python requirement to 3.9 as Biopython v1.84 requires it

**Comment by cizydorczyk** [comment]
For the life of me I cannot get this installed.

I have tried the workarounds above but always end up with dependency errors.

I can't even get the docker image running (I get errors about image not being found locally).

Any planned updates on installation instructions/updated versions that are easier to work with? As it stands, I can't get anything working.
