### ISSUE TITLE
plasmid sequence categorized as chromosome

### ISSUE THREAD

**Issue by hkaspersen** [phac-nml/mob-suite#60]
Thank you for creating a great tool! 
I am currently running some closed _E. coli_ genomes through mob_recon. In the results, I noticed that one isolate had a closed plasmid sequence categorized as "chromosome" instead of "plasmid_x". When I look in the contigs in the fasta file, I see that the actual chromosome is closed, as well as the plasmid in question. The plasmid  contig is 44425 bp long, while the chromosome is over 4 Mbp. I tried to understand what makes the program categorize the plasmid as part of the chromosome but couldn't really identify how mobsuite actually labels something as "chromosome"? A short description of why this is happening would be much appreciated!

**Comment by jrober84** [comment]
I am glad that you are liking the tool. MOB-suite takes the assumption for reconstruction that all contigs are chromosome in origin and for a contig to be considered of plasmid origin, it needs to prove that it is one through a couple of ways.  Unfortunately, It is not a simple straightforward question as say MOB-recon finds X replicon on a contig and therefore it is a plasmid. MOB-recon uses the presence of replicons, relaxases, overlap with closed plasmid reference database and circularity status to make decisions about whether a particular contig should be classified as a plasmid sequence. MOB-recon also uses other contigs to also help inform whether a set of contigs is likely a genuine plasmid. The approach is described in more detail in the MOB-suite manuscript here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6159552/.  If MOB-suite is having trouble with your specific case, you could send me the assembly and I could take a look at it for you.

**Comment by hkaspersen** [comment]
Thank you for your reply! I would very much like to send you the assembly if you feel you have the time to look at it. Where can I send it?

**Comment by jrober84** [comment]
You can

**Comment by hkaspersen** [comment]
Email sent!

**Comment by wshropshire** [comment]
Just out of curiosity, if using a database approach, why not classify chromosome on either predicted oriC sites or presence of dnaA genes and/or complemented by contig size? Reason I mention this is that it's well established that some genera have integrated plasmids/integrative conjugative elements. Not sure how you'd apply it to draft genomes unless there is scaffolding, but could be applied for closed genomes even if one could apply common sense and rule out plasmid based on size alone. Really enjoy using your tool and trying to figure out how to best apply clustering information with a large number of consensus genomes I've assembled!

**Comment by jrober84** [comment]
@wshropshire. I am glad to hear that you are enjoying the MOB-suite! The approach we designed for plasmid reconstruction is based on draft assemblies, where you would only be able to recognize the contig which contained the designated biomarkers ie. dnaA or oriC. If you had a closed genome, then you do not need to use mob_recon since you could use size and other parameters for your organism's chromosome(s) to recognize it. In the case of a complete genome, you can just run mob-typer in multimode -x and it would treat all of the contigs as plasmids and you could simply delete out the chromosome from your reports.

**Comment by jrober84** [comment]
@hkaspersen So I have figured out the issue, in the contig report file from MOB-recon, you can see your plasmid has a filtering_reason of 'repetitve element'. We pull from NCBI, IS elements to assist with the predictions and in the case where a contig consists of >= 80% repetitive sequence, it isn't trusted to define a plasmid group by itself. It would require the presence of another non-repetitive contig to be considered valid. The issue here is that someone labeled all of an IncX3 plasmid MF458176 as an IS element which is causing you plasmid to be filtered out. I will update the MOB-suite database to remove this entry. But in the meantime, you can remove it manually from the /path/to/mobsuite/db/repetitive.dna.fas  and recreate the blastdb by running makeblastdb -in /path/to/mobsuite/db/repetitive.dna.fas -dbtype nucl.

**Comment by hkaspersen** [comment]
@jrober84 thank you for your thorough investigation! I will recreate the database and run it again. So in general you would recommend to run hybrid assemblies through the multimode mob-typer instead of mob-recon? (given that the hybrid assembly is complete)

**Comment by jrober84** [comment]
@hkaspersen The reconstruction mode is meant for draft assemblies to determine which pieces fit together. If you are using a closed genome then you really don't need to use that mode since you know explicitly the complete sequence for each contig.  In this case, you could just run mob_typer --multi and type each contig and it will treat each one as a plasmid sequence. You can then filter the results to remove the chromosome. But mob_typer doesn't look at any repetitive sequences and so it can be useful to see if your circular sequence is nothing but an IS-element (which definitely has happened to me). So there is no harm in running mob_recon on a closed assembly and potentially can be helpful but it is definitely slower than just running mob_typer directly if you already know which sequences are chromosome or plasmid.

**Comment by hkaspersen** [comment]
@jrober84 Thank you for your assistance! This helped us a lot!
