### ISSUE TITLE
Updating replicon database

### ISSUE THREAD

**Issue by feanor1914** [phac-nml/mob-suite#62]
Hello,

I am trying to update the replicon database (rep.dna.fas) with a new file having the merged repllicon databases of plasmidFinder and mob_suite. I recently read that there are some discrepancies between the two databases (https://is.gd/p95DMQ). However, when using the mob_typer I get the following error: "root ERROR: Specified column for biomarker type: 1 does not exist in biomarker id field:..." for all novel entries in the database. 

Could you please help me with this issue?

Kind regards,
Ilias

**Comment by jrober84** [comment]
Hello,

the biomarker databases are pipe-delimited, they need to have the following format for the fasta files.

>rep_1|replicon_type

I would really caution against merging the databases without careful consideration. The sets of biomarkers for types are not identical so you could end up with much more multi-replicon typed plasmids. The MOB-suite database used the plasmidfinder database and expanded it so much of the new additions you would find in the MOB-suite database already. For some of the types, there were decisions made to favor the use of protein-coding genes over iterons or other non-coding sequences where possible.  You can use tools like db-check https://github.com/andersgs/db-check to identify problematic sequences in your merged file. 

The replicon database was updated not long ago and after the compass publication came out. There is definitely some discrepancies in terms of IncF subtypes that would be good to address at some point but these have not been implemented since when I tried it introduced some very odd results. 

My recommendation to you if you want to get the plasmidfindr types, then you should format it into >unique_id|replicon_type as its own replicon database and then use that explicitly when you call mob-typer and the --plasmid_replicons option. This should give you the ability to compare without introducing some wonky results.

**Comment by feanor1914** [comment]
Thank you very much for your answer, I will follow your advice and create a separate db for plasmidFinder replicons.
