### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by ilyavs** [phac-nml/mob-suite#68]
Hello,
I am using mob-suite 3.0.0 installed with conda. I ran mob_recon with -n 10 but the blast processes still seem to use only one thread. Am I missing something?
Thanks,
Ilya.

**Comment by jrober84** [comment]
Building the blast databases will always be single-threaded. Ten threads is a lot to provide the program and there may be bottlenecks that are preventing blast from using all of the available threads you are giving it. That being said, it looks like the tblastn calls are stuck at single threaded due to a previous issue with multi-threading in older versions of blast. I will add a fix to use multi-threading with tblastn. Blastn calls will use multiple threads

**Comment by ilyavs** [comment]
Thank you for your response. I was indeed referring to the tblastn processes which you noted.
Thanks,
Ilya.
