### ISSUE TITLE
show-coords instructions

### ISSUE THREAD

**Issue by tseemann** [phac-nml/mob-suite#8]
I am unable to use conda, so i wasn't sure what the show-coords step was trying to do.

```
% which show-coords 
using the path above as "conda-show-coords-path"
% ln -s conda-show-coords-path /usr/local/bin/show-coords
```

could be replaced as this on bash

```
% ln -s $(which show-coords) /usr/local/bin/show-coords
```

But it still assumes `/usr/local/bin`  is in people's PATH?

It is not in my PATH, and isn't in most HPC centres.

So I'm not sure what to do.

I have `show-coords` in my PATH as I have `mummer` 3.x installed. Is that ok?

**Comment by jrober84** [comment]
The issue is with amos and there are hardcoded full path references to /usr/local/bin/show-coords in the tool.  If you can't symlink or put show-coords into /usr/local/bin/ then the minimus2 pipeline won't work. However, previous issues have indicated that modification of the circlator minimus2 script could fix the problem https://github.com/sanger-pathogens/circlator/issues/65. This means that the circularization check won't work but mob_recon will still run and you could use unicycler assemblies with unmodified headers to identify circular contigs. In this case, mob_recon just looks for the circular=True flag in the fasta headers.
