### ISSUE TITLE
mob_init does not work because of a file sharing issue

### ISSUE THREAD

**Issue by aldertzomer** [phac-nml/mob-suite#88]
mob_init downloads a webpage with an error instead of a .tar.gz file from share.corefacility.ca. The links are broken.

**Comment by jrober84** [comment]
Sorry about that, we were migrating to a different share service and this broke the MOB-suite links. I have made the change to remove the broken link from config.json.  Because the download didn't error out, it didn't try the alternate url. We will address that in future releases but for now there will just be one url to download from. In the short term, if you edit your local config.json in the mob-suite directory to remove the share.corefacility.ca link then it should work correctly. Or you can install directly from the github repo using pip: pip install git+https://github.com/phac-nml/mob-suite.git
